#!/bin/bash 

# cvlc for mac is in this dir. Linux vlc distros have it already
dir=`dirname $0`

$dir/somafm.py >$dir/somafm.pls &
if [[ -z "$1" ]]; then
    cat  <<ENDO
    command line streaming radio - all somafm stations for now:
    usage: $FUNCNAME <showname>
    e.g.: 

    radio groovesalad
    radio dronezone
    radio dubstep
    radio deepspaceone
    radio missioncontrol
    radio lush
ENDO

else
    $dir/cvlc "http://somafm.com/$1.pls";
fi
